# Generated by Django 5.0 on 2023-12-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="contact",
            field=models.PositiveIntegerField(),
        ),
    ]
